[home]
categories="//*[contains(@class, 'departmentLinks')]/a"
    # [home.category]
link="./@href"
name="./text()"

[category]
pages="//*[contains(@class, 'pagination')]/*/*/text()[not(contains(., '<')) and not(contains(., '...')) and not(contains(., '>'))]"
products="//*[contains(@class, 'productCard')]/a"
products_links="./@href"

[product]
values_block="//*[@id='blocoValores']"
original="./*/*/span/text()"
main=""
defer=""
